package enersis.envisor.entityOld;

// Generated Apr 21, 2015 11:18:32 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "Building")
public class Building implements java.io.Serializable {

	private int id;
	private DistributionLine distributionLine;
	private String name;
	private byte flatCount;
	private byte status;
	private Date transactionTime;
	private Set<Flat> flats = new HashSet<Flat>(0);
	private Set<DistributionLineBuilding> distributionLineBuildings = new HashSet<DistributionLineBuilding>(
			0);

	public Building() {
	}

	public Building(int id, DistributionLine distributionLine, String name,
			byte flatCount, byte status, Date transactionTime) {
		this.id = id;
		this.distributionLine = distributionLine;
		this.name = name;
		this.flatCount = flatCount;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public Building(int id, DistributionLine distributionLine, String name,
			byte flatCount, byte status, Date transactionTime, Set<Flat> flats,
			Set<DistributionLineBuilding> distributionLineBuildings) {
		this.id = id;
		this.distributionLine = distributionLine;
		this.name = name;
		this.flatCount = flatCount;
		this.status = status;
		this.transactionTime = transactionTime;
		this.flats = flats;
		this.distributionLineBuildings = distributionLineBuildings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "distributionLineId", nullable = false)
	public DistributionLine getDistributionLine() {
		return this.distributionLine;
	}

	public void setDistributionLine(DistributionLine distributionLine) {
		this.distributionLine = distributionLine;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "flatCount", nullable = false)
	public byte getFlatCount() {
		return this.flatCount;
	}

	public void setFlatCount(byte flatCount) {
		this.flatCount = flatCount;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "building")
	public Set<Flat> getFlats() {
		return this.flats;
	}

	public void setFlats(Set<Flat> flats) {
		this.flats = flats;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "building")
	public Set<DistributionLineBuilding> getDistributionLineBuildings() {
		return this.distributionLineBuildings;
	}

	public void setDistributionLineBuildings(
			Set<DistributionLineBuilding> distributionLineBuildings) {
		this.distributionLineBuildings = distributionLineBuildings;
	}

}
