package enersis.envisor.entityOld;

// Generated Feb 3, 2015 10:24:48 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DistributionLineReadOutMethod generated by hbm2java
 */
@Entity
@Table(name = "DistributionLine_ReadOutMethod")
public class DistributionLineReadOutMethod implements java.io.Serializable {

	private int id;
	private DistributionLine distributionLine;
	private ReadOutMethod readOutMethod;
	private byte status;
	private Date transactionTime;

	public DistributionLineReadOutMethod() {
	}

	public DistributionLineReadOutMethod(int id,
			DistributionLine distributionLine, ReadOutMethod readOutMethod,
			byte status, Date transactionTime) {
		this.id = id;
		this.distributionLine = distributionLine;
		this.readOutMethod = readOutMethod;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "distributionLineId", nullable = false)
	public DistributionLine getDistributionLine() {
		return this.distributionLine;
	}

	public void setDistributionLine(DistributionLine distributionLine) {
		this.distributionLine = distributionLine;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "readOutMethodId", nullable = false)
	public ReadOutMethod getReadOutMethod() {
		return this.readOutMethod;
	}

	public void setReadOutMethod(ReadOutMethod readOutMethod) {
		this.readOutMethod = readOutMethod;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
