package enersis.envisor.entityOld;

// Generated Apr 21, 2015 11:18:32 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DistributionLineBuilding generated by hbm2java
 */
@Entity
@Table(name = "DistributionLine_Building")
public class DistributionLineBuilding implements java.io.Serializable {

	private int id;
	private Building building;
	private DistributionLine distributionLine;
	private byte status;
	private Date transactionTime;

	public DistributionLineBuilding() {
	}

	public DistributionLineBuilding(int id, Building building,
			DistributionLine distributionLine, byte status, Date transactionTime) {
		this.id = id;
		this.building = building;
		this.distributionLine = distributionLine;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "buildingId", nullable = false)
	public Building getBuilding() {
		return this.building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "distributionLineId", nullable = false)
	public DistributionLine getDistributionLine() {
		return this.distributionLine;
	}

	public void setDistributionLine(DistributionLine distributionLine) {
		this.distributionLine = distributionLine;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
