package enersis.envisor.entityOld;

// Generated Apr 24, 2015 12:35:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DistributionLine generated by hbm2java
 */
@Entity
@Table(name = "DistributionLine")
public class DistributionLine implements java.io.Serializable {

	private int id;
	private Project project;
	private String name;
	private String operation;
	private byte status;
	private Date transactionTime;
	private Set<Period> periods = new HashSet<Period>(0);
	private Set<DistributionLineReadOutMethod> distributionLineReadOutMethods = new HashSet<DistributionLineReadOutMethod>(
			0);
	private Set<DistributionLineBuilding> distributionLineBuildings = new HashSet<DistributionLineBuilding>(
			0);
	private Set<DistributionLineMeterType> distributionLineMeterTypes = new HashSet<DistributionLineMeterType>(
			0);
	private Set<Bill> bills = new HashSet<Bill>(0);

	public DistributionLine() {
	}

	public DistributionLine(int id, Project project, String name,
			String operation, byte status, Date transactionTime) {
		this.id = id;
		this.project = project;
		this.name = name;
		this.operation = operation;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public DistributionLine(int id, Project project, String name,
			String operation, byte status, Date transactionTime,
			Set<Period> periods,
			Set<DistributionLineReadOutMethod> distributionLineReadOutMethods,
			Set<DistributionLineBuilding> distributionLineBuildings,
			Set<DistributionLineMeterType> distributionLineMeterTypes,
			Set<Bill> bills) {
		this.id = id;
		this.project = project;
		this.name = name;
		this.operation = operation;
		this.status = status;
		this.transactionTime = transactionTime;
		this.periods = periods;
		this.distributionLineReadOutMethods = distributionLineReadOutMethods;
		this.distributionLineBuildings = distributionLineBuildings;
		this.distributionLineMeterTypes = distributionLineMeterTypes;
		this.bills = bills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "projectId", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", nullable = false, length = 15)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "operation", nullable = false, length = 15)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributionLine")
	public Set<Period> getPeriods() {
		return this.periods;
	}

	public void setPeriods(Set<Period> periods) {
		this.periods = periods;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributionLine")
	public Set<DistributionLineReadOutMethod> getDistributionLineReadOutMethods() {
		return this.distributionLineReadOutMethods;
	}

	public void setDistributionLineReadOutMethods(
			Set<DistributionLineReadOutMethod> distributionLineReadOutMethods) {
		this.distributionLineReadOutMethods = distributionLineReadOutMethods;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributionLine")
	public Set<DistributionLineBuilding> getDistributionLineBuildings() {
		return this.distributionLineBuildings;
	}

	public void setDistributionLineBuildings(
			Set<DistributionLineBuilding> distributionLineBuildings) {
		this.distributionLineBuildings = distributionLineBuildings;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributionLine")
	public Set<DistributionLineMeterType> getDistributionLineMeterTypes() {
		return this.distributionLineMeterTypes;
	}

	public void setDistributionLineMeterTypes(
			Set<DistributionLineMeterType> distributionLineMeterTypes) {
		this.distributionLineMeterTypes = distributionLineMeterTypes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributionLine")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
