package enersis.envisor.entityOld;

// Generated Apr 17, 2015 7:56:54 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HeatMeterReading generated by hbm2java
 */
@Entity
@Table(name = "HeatMeterReading")
public class HeatMeterReading implements java.io.Serializable {

	private int id;
	private HeatMeter heatMeter;
	private Period period;
	private double value;
	private Date date;
	private byte status;
	private Date transactionTime;

	public HeatMeterReading() {
	}

	public HeatMeterReading(int id, HeatMeter heatMeter, Period period,
			double value, Date date, byte status, Date transactionTime) {
		this.id = id;
		this.heatMeter = heatMeter;
		this.period = period;
		this.value = value;
		this.date = date;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "heatMeterId", nullable = false)
	public HeatMeter getHeatMeter() {
		return this.heatMeter;
	}

	public void setHeatMeter(HeatMeter heatMeter) {
		this.heatMeter = heatMeter;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "periodId", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@Column(name = "value", nullable = false, precision = 53, scale = 0)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
