package enersis.envisor.entityOld;

// Generated Feb 3, 2015 10:24:48 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MeasurementTypeUtilityType generated by hbm2java
 */
@Entity
@Table(name = "MeasurementType_UtilityType")
public class MeasurementTypeUtilityType implements java.io.Serializable {

	private byte id;
	private MeasurementType measurementType;
	private UtilityType utilityType;

	public MeasurementTypeUtilityType() {
	}

	public MeasurementTypeUtilityType(byte id, MeasurementType measurementType,
			UtilityType utilityType) {
		this.id = id;
		this.measurementType = measurementType;
		this.utilityType = utilityType;
	}

	@Id	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "measurementTypeID", nullable = false)
	public MeasurementType getMeasurementType() {
		return this.measurementType;
	}

	public void setMeasurementType(MeasurementType measurementType) {
		this.measurementType = measurementType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "utilitytypeId", nullable = false)
	public UtilityType getUtilityType() {
		return this.utilityType;
	}

	public void setUtilityType(UtilityType utilityType) {
		this.utilityType = utilityType;
	}

}
