package enersis.envisor.entityOld;

// Generated Feb 3, 2015 10:24:48 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeasurementTypeProject generated by hbm2java
 */
@Entity
@Table(name = "MeasurementType_Project")
public class MeasurementTypeProject implements java.io.Serializable {

	private int id;
	private MeasurementType measurementType;
	private Project project;
	private Date transactionTime;
	private Byte status;

	public MeasurementTypeProject() {
	}

	public MeasurementTypeProject(int id, MeasurementType measurementType,
			Project project, Date transactionTime) {
		this.id = id;
		this.measurementType = measurementType;
		this.project = project;
		this.transactionTime = transactionTime;
	}

	public MeasurementTypeProject(int id, MeasurementType measurementType,
			Project project, Date transactionTime, Byte status) {
		this.id = id;
		this.measurementType = measurementType;
		this.project = project;
		this.transactionTime = transactionTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "measurementTypeID", nullable = false)
	public MeasurementType getMeasurementType() {
		return this.measurementType;
	}

	public void setMeasurementType(MeasurementType measurementType) {
		this.measurementType = measurementType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "projectID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
