package enersis.envisor.entityOld;

// Generated Apr 17, 2015 7:56:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Period generated by hbm2java
 */
@Entity
@Table(name = "Period")
public class Period implements java.io.Serializable {

	private int id;
	private Bill bill;
	private DistributionLine distributionLine;
	private Date date;
	private byte status;
	private Date transactionTime;
	private Set<HeatCostAllocatorReading> heatCostAllocatorReadings = new HashSet<HeatCostAllocatorReading>(
			0);
	private Set<HeatMeterReading> caloriMeterReadings = new HashSet<HeatMeterReading>(
			0);
	private Set<WaterMeterReading> waterMeterReadings = new HashSet<WaterMeterReading>(
			0);

	public Period() {
	}

	public Period(int id, Bill bill, DistributionLine distributionLine,
			Date date, byte status, Date transactionTime) {
		this.id = id;
		this.bill = bill;
		this.distributionLine = distributionLine;
		this.date = date;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public Period(int id, Bill bill, DistributionLine distributionLine,
			Date date, byte status, Date transactionTime,
			Set<HeatCostAllocatorReading> heatCostAllocatorReadings,
			Set<HeatMeterReading> caloriMeterReadings,
			Set<WaterMeterReading> waterMeterReadings) {
		this.id = id;
		this.bill = bill;
		this.distributionLine = distributionLine;
		this.date = date;
		this.status = status;
		this.transactionTime = transactionTime;
		this.heatCostAllocatorReadings = heatCostAllocatorReadings;
		this.caloriMeterReadings = caloriMeterReadings;
		this.waterMeterReadings = waterMeterReadings;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "billId", nullable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "distributionLineId", nullable = false)
	public DistributionLine getDistributionLine() {
		return this.distributionLine;
	}

	public void setDistributionLine(DistributionLine distributionLine) {
		this.distributionLine = distributionLine;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "period")
	public Set<HeatCostAllocatorReading> getHeatCostAllocatorReadings() {
		return this.heatCostAllocatorReadings;
	}

	public void setHeatCostAllocatorReadings(
			Set<HeatCostAllocatorReading> heatCostAllocatorReadings) {
		this.heatCostAllocatorReadings = heatCostAllocatorReadings;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "period")
	public Set<HeatMeterReading> getCaloriMeterReadings() {
		return this.caloriMeterReadings;
	}

	public void setCaloriMeterReadings(
			Set<HeatMeterReading> caloriMeterReadings) {
		this.caloriMeterReadings = caloriMeterReadings;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "period")
	public Set<WaterMeterReading> getWaterMeterReadings() {
		return this.waterMeterReadings;
	}

	public void setWaterMeterReadings(Set<WaterMeterReading> waterMeterReadings) {
		this.waterMeterReadings = waterMeterReadings;
	}

}
