package enersis.envisor.entityOld;

// Generated Feb 26, 2015 5:20:42 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "Room")
public class Room implements java.io.Serializable {

	private int id;
	private Flat flat;
	private byte orderNo;
	private Short baseArea;
	private Short windowArea;
	private Byte glassTypeId;
	private Byte wallTypeId;
	private byte status;
	private Date transactionTime;
	private Set<HeatCostAllocator> heatCostAllocators = new HashSet<HeatCostAllocator>(
			0);

	public Room() {
	}

	public Room(int id, Flat flat, byte orderNo, byte status,
			Date transactionTime) {
		this.id = id;
		this.flat = flat;
		this.orderNo = orderNo;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public Room(int id, Flat flat, byte orderNo, Short baseArea,
			Short windowArea, Byte glassTypeId, Byte wallTypeId, byte status,
			Date transactionTime, Set<HeatCostAllocator> heatCostAllocators) {
		this.id = id;
		this.flat = flat;
		this.orderNo = orderNo;
		this.baseArea = baseArea;
		this.windowArea = windowArea;
		this.glassTypeId = glassTypeId;
		this.wallTypeId = wallTypeId;
		this.status = status;
		this.transactionTime = transactionTime;
		this.heatCostAllocators = heatCostAllocators;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flatId", nullable = false)
	public Flat getFlat() {
		return this.flat;
	}

	public void setFlat(Flat flat) {
		this.flat = flat;
	}

	@Column(name = "orderNo", nullable = false)
	public byte getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(byte orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "baseArea")
	public Short getBaseArea() {
		return this.baseArea;
	}

	public void setBaseArea(Short baseArea) {
		this.baseArea = baseArea;
	}

	@Column(name = "windowArea")
	public Short getWindowArea() {
		return this.windowArea;
	}

	public void setWindowArea(Short windowArea) {
		this.windowArea = windowArea;
	}

	@Column(name = "glassTypeId")
	public Byte getGlassTypeId() {
		return this.glassTypeId;
	}

	public void setGlassTypeId(Byte glassTypeId) {
		this.glassTypeId = glassTypeId;
	}

	@Column(name = "wallTypeId")
	public Byte getWallTypeId() {
		return this.wallTypeId;
	}

	public void setWallTypeId(Byte wallTypeId) {
		this.wallTypeId = wallTypeId;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "room")
	public Set<HeatCostAllocator> getHeatCostAllocators() {
		return this.heatCostAllocators;
	}

	public void setHeatCostAllocators(Set<HeatCostAllocator> heatCostAllocators) {
		this.heatCostAllocators = heatCostAllocators;
	}

}
