package enersis.envisor.entityOld;

// Generated Feb 3, 2015 10:24:48 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "Subscriber")
public class Subscriber implements java.io.Serializable {

	private int id;
	private Installation installation;
	private byte status;
	private Date transactionTime;

	public Subscriber() {
	}

	public Subscriber(int id, Installation installation, byte status,
			Date transactionTime) {
		this.id = id;
		this.installation = installation;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "installationId", nullable = false)
	public Installation getInstallation() {
		return this.installation;
	}

	public void setInstallation(Installation installation) {
		this.installation = installation;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
