package enersis.envisor.entityOld;

// Generated Apr 17, 2015 7:56:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WaterMeter generated by hbm2java
 */
@Entity
@Table(name = "WaterMeter")
public class WaterMeter implements java.io.Serializable {

	private int id;
	private Flat flat;
	private int serialNo;
	private byte status;
	private Date transactionTime;
	private Set<WaterMeterReading> waterMeterReadings = new HashSet<WaterMeterReading>(
			0);

	public WaterMeter() {
	}

	public WaterMeter(int id, Flat flat, int serialNo, byte status,
			Date transactionTime) {
		this.id = id;
		this.flat = flat;
		this.serialNo = serialNo;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public WaterMeter(int id, Flat flat, int serialNo, byte status,
			Date transactionTime, Set<WaterMeterReading> waterMeterReadings) {
		this.id = id;
		this.flat = flat;
		this.serialNo = serialNo;
		this.status = status;
		this.transactionTime = transactionTime;
		this.waterMeterReadings = waterMeterReadings;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flatId", nullable = false)
	public Flat getFlat() {
		return this.flat;
	}

	public void setFlat(Flat flat) {
		this.flat = flat;
	}

	@Column(name = "serialNo", nullable = false)
	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "waterMeter")
	public Set<WaterMeterReading> getWaterMeterReadings() {
		return this.waterMeterReadings;
	}

	public void setWaterMeterReadings(Set<WaterMeterReading> waterMeterReadings) {
		this.waterMeterReadings = waterMeterReadings;
	}

}
