package enersis.envisor.reporting;

public class DistributionLineBehaviours {
	
	public Integer TYPEOFDISTRIBUTIONLINE;
	public Integer COMBINATIONOFDISTRIBUTIONLINE;
	
	
	public DistributionLineBehaviours() {
	}


	public Integer getTYPEOFDISTRIBUTIONLINE() {
		return TYPEOFDISTRIBUTIONLINE;
	}


	public void setTYPEOFDISTRIBUTIONLINE(Integer tYPEOFDISTRIBUTIONLINE) {
		TYPEOFDISTRIBUTIONLINE = tYPEOFDISTRIBUTIONLINE;
	}


	public Integer getCOMBINATIONOFDISTRIBUTIONLINE() {
		return COMBINATIONOFDISTRIBUTIONLINE;
	}


	public void setCOMBINATIONOFDISTRIBUTIONLINE(Integer cOMBINATIONOFDISTRIBUTIONLINE) {
		COMBINATIONOFDISTRIBUTIONLINE = cOMBINATIONOFDISTRIBUTIONLINE;
	}
	
	
	

}
