INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Products');
INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Laptops', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Products'));
INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Power User', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Laptops'));


INSERT INTO VENDORS(NAME) VALUES ('HP');

INSERT INTO PRODUCTS(PRODUCT_CODE, NAME, DESCRIPTION, CATEGORY_ID, VENDOR_ID,PRODUCT_STOCK,TERMS_AND_CONDITIONS,REVIEW,SUITABILITY,PROCESS_NOTIFICATION,SUBMIT_NOTIFICATION)
VALUES ('HPELITE840', 'HP EliteBook 840 G2 Laptop', 'The HP EliteBook 840 thin and light notebook allows users to be ultra-productive in and out of the office. Work with confidence thanks to proven technologies, security, performance, and management features that will meet all your enterprise needs.',
        (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Power User'), currval('vendors_id_seq'), 40000,
        'OFFER valid for 1 week only','review','suitability',TRUE,FALSE);

INSERT INTO PRODUCT_VAT_RATES (PRODUCT_ID, VAT_RATE_ID, START_DATETIME)
VALUES (currval('products_id_seq'), (SELECT ID FROM VAT_RATES WHERE VAT_CODE = 'STANDARD'), TO_TIMESTAMP('2015-09-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Processor', 'Intel Core i5 processor', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Memory', '4GB DDR3L-1600 SDRAM (1 x 4GB)', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Drives', '256GB SATA TLC SSD', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Display', '14" HD+ SVA anti-flare flat LED-backlit (1600x900)', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Graphics', 'Intel HD Graphics 5500', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Audio', 'HD audio with DTS Studio Sound', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Input', 'Spill resistant backlit keyboard', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Connectivity', 'Intel I218-LM GbE (10/100/100NIC + Intel Dual Band Wireless-AC 7265 802.11a/b/g/n/ac and Bluetooth 4.0', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Power', 'HP Long Life 3-cell, 50 WHr Li-ion polymer prismatic, 65 W Smart AC Adapter', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Weight', 'Starting at 1.34 kg', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Security', 'Security lock slot (lock supplied separately, TPM 1.2/2.0, Integrated smart card reader, Fingerprint reader', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Software', 'HP BIOSphere, HP Touchpoint Manager, HP 3D DriveGuard, HP Connection Manager, HP Wireless Hotspot, HP PageLift, HP Recovery Manager, HP Support Assistant, HP ePrint', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Dimensions', '33.9 x 23.7, 2.1 cm', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Warranty', '3 year limited warranty (optional Care Packs available - sold separately', currval('products_id_seq'));

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 1, 'HP laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/c03889408_390x286.jpg');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 2, 'HP laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/c03889585_1560x1144.jpg');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 3, 'HP laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/c03889529_390x286.jpg');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 4, 'HP laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/c03889425_1560x1144.jpg');



INSERT INTO OFFERS(OFFER_REFERENCE, VERSION, PRODUCT_ID, START_DATE_TIME, END_DATE_TIME, CURRENT_VOLUME)
VALUES ('c3eeeb64-cd6c-11df-a41f-1b8d709f1111', 1, currval('products_id_seq'), TO_TIMESTAMP('2015-09-17 00:00:00.530', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2020-03-17 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 0);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 0, 199, 1030.00, 1000.00, 30.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 200, 399, 1020.00, 985.00, 35.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 400, 599, 1010.00, 970.00, 40.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 600, 699, 1000.00, 955.00, 45.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 700, 799, 990.00, 940.00, 50.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 800, 899, 980.00, 925.00, 55.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 900, 999, 970.00, 910.00, 60.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1000, 1199, 960.00, 895.00, 65.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1200, 1399, 950.00, 880.00, 70.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1400, 1599, 940.00, 865.00, 75.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1600, null, 930.00, 850.00, 80.00, 0.00);




INSERT INTO PRODUCTS(PRODUCT_CODE, NAME, DESCRIPTION, CATEGORY_ID, VENDOR_ID, PRODUCT_STOCK, TERMS_AND_CONDITIONS,REVIEW,SUITABILITY,PROCESS_NOTIFICATION,SUBMIT_NOTIFICATION)
VALUES ('HPSPECTRE',
        'HP Spectre 13-4109na x360 Convertible Laptop',
        'Time to demand more from your notebook. Function meets flexibility in the elegantly designed x360. Any way you bend it, the Spectre x360 delivers.',
        (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Power User'),
        currval('vendors_id_seq'),40000,'OFFER valid for 1 week only','review','suitability',TRUE,FALSE
        
        
);

INSERT INTO PRODUCT_VAT_RATES (PRODUCT_ID, VAT_RATE_ID, START_DATETIME)
VALUES (currval('products_id_seq'), (SELECT ID FROM VAT_RATES WHERE VAT_CODE = 'STANDARD'), TO_TIMESTAMP('2015-09-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Processor', 'Intel Core i7 processor', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Memory', '8 GB DDR3L SDRAM (onboard)', currval('products_id_seq'));

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 1, 'HP Spectre x360 laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/P5P13EA-ABU_1_1560x1144.jpg');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 2, 'HP Spectre x360 laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/P5P13EA-ABU_3_1560x1144.jpg');

INSERT INTO OFFERS(OFFER_REFERENCE, VERSION, PRODUCT_ID, START_DATE_TIME, END_DATE_TIME, CURRENT_VOLUME)
VALUES ('c3eeeb64-cd6c-11df-a41f-1b8d709f2222', 1, currval('products_id_seq'), TO_TIMESTAMP('2015-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2020-04-15 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 0);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 0, 199, 1030.00, 1000.00, 30.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 200, 399, 1020.00, 985.00, 35.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 400, 599, 1010.00, 970.00, 40.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 600, 699, 1000.00, 955.00, 45.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 700, 799, 990.00, 940.00, 50.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 800, 899, 980.00, 925.00, 55.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 900, 999, 970.00, 910.00, 60.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1000, 1199, 960.00, 895.00, 65.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1200, 1399, 950.00, 880.00, 70.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1400, 1599, 940.00, 865.00, 75.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1600, null, 930.00, 850.00, 80.00,0.00);
