INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('IT Products', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Products'));
INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Desktops', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'IT Products'));
INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Printers', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'IT Products'));
INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Ink', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'IT Products'));


UPDATE CATEGORIES SET PARENT_ID = (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'IT Products') WHERE CATEGORY_NAME = 'Laptops';
UPDATE CATEGORIES SET CATEGORY_NAME = 'Power User Laptops' WHERE CATEGORY_NAME = 'Power User';
