DELETE FROM BUYER_PROFILES WHERE USER_ID = (SELECT ID FROM USERS WHERE USER_NAME = 'oliver.squires@ishoal.com');

INSERT INTO CONTACTS(TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, PHONE_NUMBER)
VALUES ('Mr', 'Oliver', 'Squires', 'oliver.squires@ishoal.com', '0113 9876543');

INSERT INTO ADDRESSES(DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES ('Sales', 'Shoal Demo Company', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BANK_ACCOUNTS(ACCOUNT_NAME, SORTCODE, ACCOUNT_NUMBER, BANK_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POST_CODE)
VALUES ('Shoal Demo Company', '11-22-33', '12345678', 'HSBC', 'Bank House', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BUYER_PROFILES (USER_ID, ORGANISATION_ID, CONTACT_ID, DELIVERY_ADDRESS_ID, BANK_ACCOUNT_ID, COMPLETED, VERSION)
VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'oliver.squires@ishoal.com'),
        (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal Ltd'),
        currval('contacts_id_seq'), currval('addresses_id_seq'), currval('bank_accounts_id_seq'), TRUE, 1);


DELETE FROM BUYER_PROFILES WHERE USER_ID = (SELECT ID FROM USERS WHERE USER_NAME = 'andrew.salkeld@ishoal.com');

INSERT INTO CONTACTS(TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, PHONE_NUMBER)
VALUES ('Mr', 'Andrew', 'Salkeld', 'andrew.salkeld@ishoal.com', '0113 9876543');

INSERT INTO ADDRESSES(DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES ('Sales', 'Shoal Demo Company', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BANK_ACCOUNTS(ACCOUNT_NAME, SORTCODE, ACCOUNT_NUMBER, BANK_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POST_CODE)
VALUES ('Shoal Demo Company', '11-22-33', '12345678', 'HSBC', 'Bank House', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BUYER_PROFILES (USER_ID, ORGANISATION_ID, CONTACT_ID, DELIVERY_ADDRESS_ID, BANK_ACCOUNT_ID, COMPLETED, VERSION)
VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'andrew.salkeld@ishoal.com'),
        (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal Ltd'),
        currval('contacts_id_seq'), currval('addresses_id_seq'), currval('bank_accounts_id_seq'), TRUE, 1);


DELETE FROM BUYER_PROFILES WHERE USER_ID = (SELECT ID FROM USERS WHERE USER_NAME = 'christopher.salkeld@ishoal.com');

INSERT INTO CONTACTS(TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, PHONE_NUMBER)
VALUES ('Mr', 'Chris', 'Salkeld', 'christopher.salkeld@ishoal.com', '0113 9876543');

INSERT INTO ADDRESSES(DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES ('Sales', 'Shoal Demo Company', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BANK_ACCOUNTS(ACCOUNT_NAME, SORTCODE, ACCOUNT_NUMBER, BANK_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POST_CODE)
VALUES ('Shoal Demo Company', '11-22-33', '12345678', 'HSBC', 'Bank House', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BUYER_PROFILES (USER_ID, ORGANISATION_ID, CONTACT_ID, DELIVERY_ADDRESS_ID, BANK_ACCOUNT_ID, COMPLETED, VERSION)
VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'christopher.salkeld@ishoal.com'),
        (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal Ltd'),
        currval('contacts_id_seq'), currval('addresses_id_seq'), currval('bank_accounts_id_seq'), TRUE, 1);


DELETE FROM BUYER_PROFILES WHERE USER_ID = (SELECT ID FROM USERS WHERE USER_NAME = 'andy.kerr@ishoal.com');

INSERT INTO CONTACTS(TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, PHONE_NUMBER)
VALUES ('Mr', 'Andy', 'Kerr', 'andy.kerr@ishoal.com', '0113 9876543');

INSERT INTO ADDRESSES(DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES ('Sales', 'Shoal Demo Company', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BANK_ACCOUNTS(ACCOUNT_NAME, SORTCODE, ACCOUNT_NUMBER, BANK_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POST_CODE)
VALUES ('Shoal Demo Company', '11-22-33', '12345678', 'HSBC', 'Bank House', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BUYER_PROFILES (USER_ID, ORGANISATION_ID, CONTACT_ID, DELIVERY_ADDRESS_ID, BANK_ACCOUNT_ID, COMPLETED, VERSION)
VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'andy.kerr@ishoal.com'),
        (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal Ltd'),
        currval('contacts_id_seq'), currval('addresses_id_seq'), currval('bank_accounts_id_seq'), TRUE, 1);


DELETE FROM BUYER_PROFILES WHERE USER_ID = (SELECT ID FROM USERS WHERE USER_NAME = 'simon.urquhart@ishoal.com');

INSERT INTO CONTACTS(TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, PHONE_NUMBER)
VALUES ('Mr', 'Simon', 'Urquhart', 'simon.urquhart@ishoal.com', '0113 9876543');

INSERT INTO ADDRESSES(DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES ('Sales', 'Shoal Demo Company', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BANK_ACCOUNTS(ACCOUNT_NAME, SORTCODE, ACCOUNT_NUMBER, BANK_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POST_CODE)
VALUES ('Shoal Demo Company', '11-22-33', '12345678', 'HSBC', 'Bank House', 'High Street', 'Bramham', 'Wetherby', 'LS23 6QR');

INSERT INTO BUYER_PROFILES (USER_ID, ORGANISATION_ID, CONTACT_ID, DELIVERY_ADDRESS_ID, BANK_ACCOUNT_ID, COMPLETED, VERSION)
VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'simon.urquhart@ishoal.com'),
        (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal Ltd'),
        currval('contacts_id_seq'), currval('addresses_id_seq'), currval('bank_accounts_id_seq'), TRUE, 1);

