INSERT INTO PRODUCTS(PRODUCT_CODE, NAME, DESCRIPTION, CATEGORY_ID, VENDOR_ID,PRODUCT_STOCK, TERMS_AND_CONDITIONS,REVIEW,SUITABILITY,PROCESS_NOTIFICATION,SUBMIT_NOTIFICATION)
VALUES ('HPPAVILION550Z',
        'HP Pavilion 550z Windows 7 Desktop',
        'While other towers have been standing still, HP has revolutionized the category. From magnified performance and reliability, to its colorful redesign, this HP Pavilion is the best thing to happen to towers in over 20 years.',
        (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Desktops'),
        currval('vendors_id_seq'),
        40000,
        'OFFER valid for 1 week only','review','suitability',TRUE,FALSE
        
);

INSERT INTO PRODUCT_VAT_RATES (PRODUCT_ID, VAT_RATE_ID, START_DATETIME)
VALUES (currval('products_id_seq'), (SELECT ID FROM VAT_RATES WHERE VAT_CODE = 'STANDARD'), TO_TIMESTAMP('2015-09-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Processor', 'AMD A6-7400K processor dual-core [3.5GHz; 1MB L2 Cache]', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Memory', '8GB DDR3-1600 DIMM (2x4GB) RAM', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Operating System', 'Windows 7 Professional 64', currval('products_id_seq'));

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 1, 'HP Pavillion 550z', 'http://demo.the-shoal.com/productimages/c04717472.png');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 2, 'HP Pavillion 550z', 'http://demo.the-shoal.com/productimages/c04717360.png');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 3, 'HP Pavillion 550z', 'http://demo.the-shoal.com/productimages/c04718165.png');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 4, 'HP Pavillion 550z', 'http://demo.the-shoal.com/productimages/c04725825.png');


INSERT INTO OFFERS(OFFER_REFERENCE, VERSION, PRODUCT_ID, START_DATE_TIME, END_DATE_TIME, CURRENT_VOLUME)
VALUES ('HPPAVILION550Z', 1, currval('products_id_seq'), TO_TIMESTAMP('2015-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2020-12-15 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 0);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 0, 199, 400.00, 390.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 200, 399, 395.00, 385.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 400, 599, 390.00, 380.00, 10.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 600, 699, 385.00, 375.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 700, 799, 375.00, 365.00, 10.00, 0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 800, 899, 365.00, 355.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 900, 999, 350.00, 340.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1000, 1199, 335.00, 325.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1200, 1399, 325.00, 315.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1400, 1599, 315.00, 305.00, 10.00,0.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, AGENCY_MARGIN, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1600, null, 310.00, 300.00, 10.00,0.00);
