INSERT INTO ORGANISATIONS(NAME) VALUES ('Shoal');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME, ORGANISATION_ID)
    VALUES ('oliver.squires@ishoal.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Oliver', 'Squires', (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Shoal'));

INSERT INTO USER_ROLES(USER_ID, ROLE_ID)
VALUES (
  (SELECT ID FROM USERS WHERE USER_NAME = 'oliver.squires@ishoal.com'),
  (SELECT ID FROM ROLES WHERE NAME = 'BUYER')
);

INSERT INTO USER_ROLES(USER_ID, ROLE_ID)
VALUES (
  (SELECT ID FROM USERS WHERE USER_NAME = 'oliver.squires@ishoal.com'),
  (SELECT ID FROM ROLES WHERE NAME = 'ADMIN')
);

