INSERT INTO ORGANISATIONS(NAME) VALUES ('Slate Rock & Gravel Co');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME, ORGANISATION_ID)
VALUES ('fred@srgc.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Fred', 'Flintstone', (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Slate Rock & Gravel Co'));

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'fred@srgc.com'), 'BUYER');


INSERT INTO ORGANISATIONS(NAME) VALUES ('Pawtucket Patriot Brewery');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME, ORGANISATION_ID)
VALUES ('peter@ppb.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Peter', 'Griffin', (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Pawtucket Patriot Brewery'));

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES ((SELECT ID FROM USERS WHERE USER_NAME = 'peter@ppb.com'), 'PENDING_AUTHORISATION');

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Convertibles', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Laptops'));


-- Order 1 - confirmed order for 'tom@bosl.co.uk' with a credit

INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME, INVOICE_DATE)
VALUES((SELECT ID FROM USERS WHERE USER_NAME = 'tom@bosl.co.uk'),
       (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Bramham Office Services Ltd'),
       (SELECT ID FROM VENDORS WHERE NAME = 'HP'),
       '14b95c9e-1c54-46b1-a825-befe12873e66', 'CONFIRMED', 'UNPAID', 1, TIMESTAMP'2015-09-17 00:00:00Z', TIMESTAMP'2015-09-18 00:00:00Z', DATE'2017-09-08');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = '14b95c9e-1c54-46b1-a825-befe12873e66'), TRUE, TRUE, 'BOSL Ltd', 'Sales', 'BOSL House', '42 Letsby Avenue', 'Bramham', 'Wetherby', 'LS22 2XX');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = '14b95c9e-1c54-46b1-a825-befe12873e66'),
  (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840'),
  (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')),
  (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 0),
  (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 1000),
  750, 772500.00, 20, 154500.00, TIMESTAMP'2015-09-17 00:00:00Z', TIMESTAMP'2015-09-18 00:00:00Z');

INSERT INTO BUYER_CREDITS(ORDER_LINE_ID, NET_AMOUNT, VAT_AMOUNT, CREATED_DATETIME)
VALUES((SELECT L.ID FROM ORDER_LINES L JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = '14b95c9e-1c54-46b1-a825-befe12873e66'), 75000, 15000, TIMESTAMP'2015-09-18 00:00:00Z');


-- Order 2 - requested order for 'tom@bosl.co.uk'
INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME, INVOICE_DATE)
VALUES((SELECT ID FROM USERS WHERE USER_NAME = 'tom@bosl.co.uk'),
       (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Bramham Office Services Ltd'),
       (SELECT ID FROM VENDORS WHERE NAME = 'HP'),
       'c175979f-d52a-4fe9-9afd-2955fde64403', 'PROCESSING', 'UNPAID', 0, TIMESTAMP'2015-09-17 00:00:00Z', TIMESTAMP'2015-09-17 00:00:00Z', DATE'2017-09-09');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = 'c175979f-d52a-4fe9-9afd-2955fde64403'), TRUE, TRUE, 'BOSL Ltd', 'Sales', 'BOSL House', '42 Letsby Avenue', 'Bramham', 'Wetherby', 'LS22 2XX');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = 'c175979f-d52a-4fe9-9afd-2955fde64403'),
  (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840'),
  (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')),
  (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 0),
  (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 0),
  150, 154500.00, 20, 30900.00, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-17 00:00:00');


-- Order 3 - confirmed order for 'melissa@niddhoney.co.uk'
INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME, INVOICE_DATE)
VALUES((SELECT ID FROM USERS WHERE USER_NAME = 'melissa@niddhoney.co.uk'),
       (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Nidderdale Honey Ltd'),
       (SELECT ID FROM VENDORS WHERE NAME = 'HP'),
       'bea39549-d294-4bcb-bfa0-5d20b657e1bb', 'CONFIRMED', 'UNPAID', 1, TIMESTAMP'2015-09-17 00:00:00Z', TIMESTAMP'2015-09-18 00:00:00Z', DATE'2017-09-10');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = 'bea39549-d294-4bcb-bfa0-5d20b657e1bb'), TRUE, FALSE, 'Nidd Honey Ltd', 'Head Office', 'The Hive', '1 Busby Way', 'Bewerley', 'Harrogate', 'HG3 5BZ');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = 'bea39549-d294-4bcb-bfa0-5d20b657e1bb'), FALSE, TRUE, 'Nidd Honey Ltd', 'Sales', 'The Hive', '1 Busby Way', 'Bewerley', 'Harrogate', 'HG3 5BZ');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = 'bea39549-d294-4bcb-bfa0-5d20b657e1bb'), (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840'), (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')), (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 1000), (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 1000), 500, 465000.00, 20, 93000.00, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-17 00:00:00');


-- Order 4 - confirmed order for 'fred@srgc.com.' with a credit and a credit applied
INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME, INVOICE_DATE)
VALUES((SELECT ID FROM USERS WHERE USER_NAME = 'fred@srgc.com'),
       (SELECT ID FROM ORGANISATIONS WHERE NAME = 'Slate Rock & Gravel Co'),
       (SELECT ID FROM VENDORS WHERE NAME = 'HP'),
       '6b15aecf-e9d4-404f-86ee-067c14401045', 'CONFIRMED', 'PAID', 1, TIMESTAMP'2015-11-04 00:00:00Z', TIMESTAMP'2015-01-04 00:00:00Z', DATE'2017-09-012');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = '6b15aecf-e9d4-404f-86ee-067c14401045'), TRUE, TRUE, 'SRGC Plc', 'Head Office', null, '20 High Street', null, 'Harrogate', 'HG1 1AA');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES((SELECT ID FROM ORDERS WHERE REFERENCE = '6b15aecf-e9d4-404f-86ee-067c14401045'), (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840'), (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')), (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 0), (SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = (SELECT ID FROM OFFERS WHERE PRODUCT_ID = (SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840')) AND MIN_VOLUME = 1000), 750, 772500.00, 20, 154500.00, TIMESTAMP'2015-01-04 00:00:00', TIMESTAMP'2015-01-04 00:00:00');

INSERT INTO BUYER_CREDITS(ORDER_LINE_ID, NET_AMOUNT, VAT_AMOUNT, CREATED_DATETIME)
VALUES((SELECT L.ID FROM ORDER_LINES L JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = '6b15aecf-e9d4-404f-86ee-067c14401045'), 75000, 15000, TIMESTAMP'2015-11-04 00:00:00Z');

INSERT INTO BUYER_APPLIED_CREDITS(BUYER_CREDIT_ID, STATUS, SPEND_TYPE, NET_AMOUNT, VAT_AMOUNT, GROSS_AMOUNT, ORIGINAL_ORDER_REFERENCE, ORIGINAL_ORDER_LINE_PRODUCT_CODE, ORDER_SPENT_ON_REFERENCE, CREATED_DATETIME)
VALUES((SELECT BC.ID FROM BUYER_CREDITS BC JOIN ORDER_LINES L ON L.ID = BC.ORDER_LINE_ID JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = '6b15aecf-e9d4-404f-86ee-067c14401045'),
       'CONFIRMED', 'SPEND', 18750, 3750, 22500, '6b15aecf-e9d4-404f-86ee-067c14401045', 'HPELITE840', 'bea39549-d294-4bcb-bfa0-5d20b657e1bb', TIMESTAMP'2015-11-05 00:00:00Z');


INSERT INTO PRODUCTS(PRODUCT_CODE, NAME, DESCRIPTION, CATEGORY_ID, VENDOR_ID, PRODUCT_STOCK, TERMS_AND_CONDITIONS)
VALUES ('HPSPIRIT',
        'HP SPIRIT 13-4109na x360 Convertible Laptop',
        'Time to demand more from your notebook. Function meets flexibility in the elegantly designed x360. Any way you bend it, the Spirit x360 delivers.',
        (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Convertibles'),
        (SELECT ID FROM VENDORS WHERE NAME = 'HP'),
        40000,
        'OFFER valid for 1 week only');

INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Processor', 'Intel Core i7 processor', currval('products_id_seq'));
INSERT INTO PRODUCT_SPECS(SPEC_TYPE, SPEC_VALUE, PRODUCT_ID) VALUES ('Memory', '8 GB DDR3L SDRAM (onboard)', currval('products_id_seq'));

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 1, 'HP Spirit x360 laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/P5P13EA-ABU_1_1560x1144.jpg');

INSERT INTO PRODUCT_IMAGES(PRODUCT_ID, PRIORITY, DESCRIPTION, URL)
VALUES(currval('products_id_seq'), 2, 'HP Spirit x360 laptop', 'http://www.www8-hp.com/h22175/UKStore/Html/Merch/Images/P5P13EA-ABU_3_1560x1144.jpg');

INSERT INTO OFFERS(VERSION, PRODUCT_ID, START_DATE_TIME, END_DATE_TIME, CURRENT_VOLUME)
VALUES (1, currval('products_id_seq'), TO_TIMESTAMP('2015-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2020-04-15 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 36);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE,  DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 0, 999, 2030.00, 1930.00, 20.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 1000, 1999, 1930.00, 1820.00, 20.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 2000, 2999, 1830.00, 1710.00, 20.00);

INSERT INTO OFFER_PRICE_BANDS(OFFER_ID, MIN_VOLUME, MAX_VOLUME, BUYER_PRICE, VENDOR_PRICE, DISTRIBUTOR_MARGIN)
VALUES (currval('offers_id_seq'), 3000, null, 1730.00, 1600.00, 20.00);

INSERT INTO PRODUCT_VAT_RATES (PRODUCT_ID, VAT_RATE_ID, START_DATETIME)
VALUES (
  currval('products_id_seq'),
  (SELECT ID FROM VAT_RATES WHERE VAT_CODE = 'STANDARD'),
  TO_TIMESTAMP('2015-09-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
);

