INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Products');

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Laptops', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Products'));

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Power User', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Laptops'));

UPDATE PRODUCTS SET CATEGORY_ID = (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Power User') WHERE PRODUCT_CODE = 'HPELITE840';
