--------------------------------------------------------
--  File created - Monday-June-23-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ANCHOR_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EPOOQ"."ANCHOR_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMUNITY_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EPOOQ"."COMMUNITY_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KEY_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EPOOQ"."KEY_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PICTURE_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EPOOQ"."PICTURE_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ANCHOR_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."ANCHOR_TBL" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"CREATED" DATE DEFAULT SYSDATE, 
	"PLACE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"COMMUNITY_ID" NUMBER, 
	"PICTURE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMUNITY_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."COMMUNITY_TBL" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"PICTURE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KEY_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."KEY_TBL" 
   (	"ID" NUMBER, 
	"QUESTION" VARCHAR2(100 BYTE), 
	"AGE" NUMBER(*,0), 
	"COMMUNITY_ID" NUMBER, 
	"PICTURE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PICTURE_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."PICTURE_TBL" 
   (	"ID" NUMBER, 
	"MIME_TYPE" VARCHAR2(50 BYTE), 
	"DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SETTINGS_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."SETTINGS_TBL" 
   (	"KEY" VARCHAR2(50 BYTE), 
	"VALUE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STORY_TBL
--------------------------------------------------------

  CREATE TABLE "EPOOQ"."STORY_TBL" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"PLACE" VARCHAR2(50 BYTE), 
	"COMMUNITY_ID" NUMBER, 
	"READY" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANCHOR_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."ANCHOR_TBL_PK" ON "EPOOQ"."ANCHOR_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMUNITY_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."COMMUNITY_TBL_PK" ON "EPOOQ"."COMMUNITY_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KEY_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."KEY_TBL_PK" ON "EPOOQ"."KEY_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PICTURE_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."PICTURE_TBL_PK" ON "EPOOQ"."PICTURE_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SETTINGS_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."SETTINGS_TBL_PK" ON "EPOOQ"."SETTINGS_TBL" ("KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STORY_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EPOOQ"."STORY_TBL_PK" ON "EPOOQ"."STORY_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANCHOR_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."ANCHOR_TBL" ADD CONSTRAINT "ANCHOR_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."ANCHOR_TBL" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."ANCHOR_TBL" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."ANCHOR_TBL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."COMMUNITY_TBL" ADD CONSTRAINT "COMMUNITY_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."COMMUNITY_TBL" MODIFY ("PICTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."COMMUNITY_TBL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."COMMUNITY_TBL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KEY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."KEY_TBL" ADD CONSTRAINT "KEY_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."KEY_TBL" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."KEY_TBL" MODIFY ("QUESTION" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."KEY_TBL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PICTURE_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."PICTURE_TBL" ADD CONSTRAINT "PICTURE_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."PICTURE_TBL" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."PICTURE_TBL" MODIFY ("MIME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."PICTURE_TBL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SETTINGS_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."SETTINGS_TBL" ADD CONSTRAINT "SETTINGS_TBL_PK" PRIMARY KEY ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."SETTINGS_TBL" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."SETTINGS_TBL" MODIFY ("KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."STORY_TBL" ADD CONSTRAINT "STORY_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EPOOQ"."STORY_TBL" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."STORY_TBL" MODIFY ("READY" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."STORY_TBL" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "EPOOQ"."STORY_TBL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANCHOR_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."ANCHOR_TBL" ADD CONSTRAINT "ANCHOR_TBL_FK1" FOREIGN KEY ("COMMUNITY_ID")
	  REFERENCES "EPOOQ"."COMMUNITY_TBL" ("ID") ENABLE;
  ALTER TABLE "EPOOQ"."ANCHOR_TBL" ADD CONSTRAINT "ANCHOR_TBL_FK2" FOREIGN KEY ("PICTURE_ID")
	  REFERENCES "EPOOQ"."PICTURE_TBL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMUNITY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."COMMUNITY_TBL" ADD CONSTRAINT "COMMUNITY_TBL_FK1" FOREIGN KEY ("PICTURE_ID")
	  REFERENCES "EPOOQ"."PICTURE_TBL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KEY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."KEY_TBL" ADD CONSTRAINT "KEY_TBL_FK1" FOREIGN KEY ("COMMUNITY_ID")
	  REFERENCES "EPOOQ"."COMMUNITY_TBL" ("ID") ENABLE;
  ALTER TABLE "EPOOQ"."KEY_TBL" ADD CONSTRAINT "KEY_TBL_FK2" FOREIGN KEY ("PICTURE_ID")
	  REFERENCES "EPOOQ"."PICTURE_TBL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORY_TBL
--------------------------------------------------------

  ALTER TABLE "EPOOQ"."STORY_TBL" ADD CONSTRAINT "STORY_TBL_FK1" FOREIGN KEY ("COMMUNITY_ID")
	  REFERENCES "EPOOQ"."COMMUNITY_TBL" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANCHOR_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EPOOQ"."ANCHOR_TBL_TRG" 
BEFORE INSERT ON ANCHOR_TBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ANCHOR_TBL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EPOOQ"."ANCHOR_TBL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMUNITY_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EPOOQ"."COMMUNITY_TBL_TRG" 
BEFORE INSERT ON COMMUNITY_TBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT COMMUNITY_TBL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EPOOQ"."COMMUNITY_TBL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KEY_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EPOOQ"."KEY_TBL_TRG" 
BEFORE INSERT ON KEY_TBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT KEY_TBL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EPOOQ"."KEY_TBL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PICTURE_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EPOOQ"."PICTURE_TBL_TRG" 
BEFORE INSERT ON PICTURE_TBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PICTURE_TBL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EPOOQ"."PICTURE_TBL_TRG" ENABLE;
