INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Products');

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Laptops', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Products'));

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Power User', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Laptops'));

INSERT INTO CATEGORIES (CATEGORY_NAME, PARENT_ID) VALUES ('Convertibles', (SELECT ID FROM CATEGORIES WHERE CATEGORY_NAME = 'Laptops'));

