SET @PRODUCT_ID = SELECT ID FROM PRODUCTS WHERE PRODUCT_CODE = 'HPELITE840';
SET @OFFER_ID = SELECT ID FROM OFFERS WHERE PRODUCT_ID = @PRODUCT_ID;

SET @PRICE_BAND_ID_1 = SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = @OFFER_ID AND MIN_VOLUME = 0;
SET @PRICE_BAND_ID_2 = SELECT ID FROM OFFER_PRICE_BANDS WHERE OFFER_ID = @OFFER_ID AND MIN_VOLUME = 1000;

-- Order 1 - confirmed order for 'tom@bosl.co.uk' with a credit
SET @BUYER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'tom@bosl.co.uk';
SET @BUYER_ORG_ID = SELECT O.ID FROM ORGANISATIONS O JOIN BUYER_PROFILES P ON P.ORGANISATION_ID = O.ID WHERE P.USER_ID = @BUYER_ID;
SET @VENDOR_ID = SELECT ID FROM VENDORS WHERE NAME = 'HP';

INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@BUYER_ID, @BUYER_ORG_ID, @VENDOR_ID, 'P22Q-8HG-MBA-M76A', 'CONFIRMED', 'UNPAID', 1, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-18 00:00:00');

SET @ORDER_ID = SELECT ID FROM ORDERS WHERE REFERENCE = 'P22Q-8HG-MBA-M76A';

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
    VALUES(@ORDER_ID, TRUE, TRUE, 'BOSL Ltd', 'Sales', 'BOSL House', '42 Letsby Avenue', 'Bramham', 'Wetherby', 'LS22 2XX');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@ORDER_ID, @PRODUCT_ID, @OFFER_ID, @PRICE_BAND_ID_1, @PRICE_BAND_ID_2, 750, 772500.00, 20, 154500.00, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-18 00:00:00');

SET @ORDER_LINE_ID = SELECT L.ID FROM ORDER_LINES L JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = 'P22Q-8HG-MBA-M76A';
INSERT INTO BUYER_CREDITS(ORDER_LINE_ID, NET_AMOUNT, VAT_AMOUNT, CREATED_DATETIME)
  VALUES(@ORDER_LINE_ID, 75000, 15000, TIMESTAMP'2015-09-18 00:00:00');


-- Order 2 - requested order for 'tom@bosl.co.uk'
SET @BUYER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'tom@bosl.co.uk';
SET @BUYER_ORG_ID = SELECT O.ID FROM ORGANISATIONS O JOIN BUYER_PROFILES P ON P.ORGANISATION_ID = O.ID WHERE P.USER_ID = @BUYER_ID;
SET @VENDOR_ID = SELECT ID FROM VENDORS WHERE NAME = 'HP';

INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@BUYER_ID, @BUYER_ORG_ID, @VENDOR_ID, 'F38V-8HG-MBA-K40E', 'PROCESSING', 'UNPAID', 0, TIMESTAMP'2015-09-17 00:00:00Z', TIMESTAMP'2015-09-17 00:00:00Z');

SET @ORDER_ID = SELECT ID FROM ORDERS WHERE REFERENCE = 'F38V-8HG-MBA-K40E';

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
  VALUES(@ORDER_ID, TRUE, TRUE, 'BOSL Ltd', 'Sales', 'BOSL House', '42 Letsby Avenue', 'Bramham', 'Wetherby', 'LS22 2XX');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@ORDER_ID, @PRODUCT_ID, @OFFER_ID, @PRICE_BAND_ID_1, @PRICE_BAND_ID_1, 150, 154500.00, 20, 30900.00, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-17 00:00:00');


-- Order 3 - confirmed order for 'melissa@niddhoney.co.uk'
SET @BUYER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'melissa@niddhoney.co.uk';
SET @BUYER_ORG_ID = SELECT O.ID FROM ORGANISATIONS O JOIN BUYER_PROFILES P ON P.ORGANISATION_ID = O.ID WHERE P.USER_ID = @BUYER_ID;
SET @VENDOR_ID = SELECT ID FROM VENDORS WHERE NAME = 'HP';

INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@BUYER_ID, @BUYER_ORG_ID, @VENDOR_ID, 'GLHX-8HG-MBA-H3KU', 'CONFIRMED', 'UNPAID', 1, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-18 00:00:00');

SET @ORDER_ID = SELECT ID FROM ORDERS WHERE REFERENCE = 'GLHX-8HG-MBA-H3KU';

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
  VALUES(@ORDER_ID, TRUE, FALSE, 'Nidd Honey Ltd', 'Head Office', 'The Hive', '1 Busby Way', 'Bewerley', 'Harrogate', 'HG3 5BZ');

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
  VALUES(@ORDER_ID, FALSE, TRUE, 'Nidd Honey Ltd', 'Sales', 'The Hive', '1 Busby Way', 'Bewerley', 'Harrogate', 'HG3 5BZ');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
  VALUES(@ORDER_ID, @PRODUCT_ID, @OFFER_ID, @PRICE_BAND_ID_2, @PRICE_BAND_ID_2, 500, 465000.00, 20, 93000.00, TIMESTAMP'2015-09-17 00:00:00', TIMESTAMP'2015-09-17 00:00:00');


-- Order 4 - confirmed order for 'fred@srgc.com.' with a credit and a credit applied
SET @BUYER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'fred@srgc.com';
SET @BUYER_ORG_ID = SELECT O.ID FROM ORGANISATIONS O JOIN BUYER_PROFILES P ON P.ORGANISATION_ID = O.ID WHERE P.USER_ID = @BUYER_ID;
SET @VENDOR_ID = SELECT ID FROM VENDORS WHERE NAME = 'HP';

INSERT INTO ORDERS(BUYER_ID, BUYER_ORGANISATION_ID, VENDOR_ID, REFERENCE, STATUS, PAYMENT_STATUS, VERSION, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES(@BUYER_ID, @BUYER_ORG_ID, @VENDOR_ID, 'VVF4-HBH-MBA-7B4E', 'CONFIRMED', 'PAID', 1, TIMESTAMP'2015-11-04 00:00:00', TIMESTAMP'2015-01-04 00:00:00');

SET @ORDER_ID = SELECT ID FROM ORDERS WHERE REFERENCE = 'VVF4-HBH-MBA-7B4E';

INSERT INTO ORDER_ADDRESSES(ORDER_ID, IS_INVOICE_ADDRESS, IS_DELIVERY_ADDRESS, ORGANISATION_NAME, DEPARTMENT_NAME, BUILDING_NAME, STREET_ADDRESS, LOCALITY, POST_TOWN, POSTCODE)
VALUES(@ORDER_ID, TRUE, TRUE, 'SRGC Plc', 'Head Office', null, '20 High Street', null, 'Harrogate', 'HG1 1AA');

INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, OFFER_ID, INITIAL_PRICE_BAND_ID, CURRENT_PRICE_BAND_ID, QUANTITY, NET_AMOUNT, VAT_RATE, VAT_AMOUNT, CREATED_DATETIME, MODIFIED_DATETIME)
VALUES(@ORDER_ID, @PRODUCT_ID, @OFFER_ID, @PRICE_BAND_ID_1, @PRICE_BAND_ID_2, 750, 772500.00, 20, 154500.00, TIMESTAMP'2015-01-04 00:00:00', TIMESTAMP'2015-01-04 00:00:00');

SET @ORDER_LINE_ID = SELECT L.ID FROM ORDER_LINES L JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = 'VVF4-HBH-MBA-7B4E';
INSERT INTO BUYER_CREDITS(ORDER_LINE_ID, NET_AMOUNT, VAT_AMOUNT, CREATED_DATETIME)
VALUES(@ORDER_LINE_ID, 75000, 15000, TIMESTAMP'2015-11-04 00:00:00');

SET @BUYER_CREDITS_ID = SELECT BC.ID FROM BUYER_CREDITS BC JOIN ORDER_LINES L ON L.ID = BC.ORDER_LINE_ID JOIN ORDERS O ON O.ID = L.ORDER_ID WHERE O.REFERENCE = 'VVF4-HBH-MBA-7B4E';
INSERT INTO BUYER_APPLIED_CREDITS(BUYER_CREDIT_ID, STATUS, SPEND_TYPE, NET_AMOUNT, VAT_AMOUNT, GROSS_AMOUNT, ORIGINAL_ORDER_REFERENCE, ORIGINAL_ORDER_LINE_PRODUCT_CODE, ORDER_SPENT_ON_REFERENCE, CREATED_DATETIME)
VALUES(@BUYER_CREDIT_ID, 'CONFIRMED', 'SPEND', 18750, 3750, 22500, 'VVF4-HBH-MBA-7B4E', 'HPELITE840', 'GLHX-8HG-MBA-H3KU', TIMESTAMP'2015-11-05 00:00:00');