SET @BUYER_ROLE_ID = 'BUYER';
SET @ADMIN_ROLE_ID = 'ADMIN';

-- oliver.squires@ishoal.com
INSERT INTO ORGANISATIONS(NAME) VALUES ('Shoal');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME)
    VALUES ('oliver.squires@ishoal.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Oliver', 'Squires');

SET @USER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'oliver.squires@ishoal.com';

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (@USER_ID, @BUYER_ROLE_ID);

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (@USER_ID, @ADMIN_ROLE_ID);

-- melissa@niddhoney.co.uk
INSERT INTO ORGANISATIONS(NAME) VALUES ('Nidderdale Honey Ltd');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME)
VALUES ('melissa@niddhoney.co.uk', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Melissa', 'Apis');

SET @USER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'melissa@niddhoney.co.uk';

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (@USER_ID, @BUYER_ROLE_ID);

-- tom@bosl.co.uk
INSERT INTO ORGANISATIONS(NAME) VALUES ('Bramham Office Services Ltd');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME)
VALUES ('tom@bosl.co.uk', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Tom', 'Fake');

SET @USER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'tom@bosl.co.uk';

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (@USER_ID, @BUYER_ROLE_ID);

-- fred@srgc.com
INSERT INTO ORGANISATIONS(NAME) VALUES ('Slate Rock & Gravel Co');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME)
VALUES ('fred@srgc.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Fred', 'Flintstone');

SET @USER_ID = SELECT ID FROM USERS WHERE USER_NAME = 'fred@srgc.com';

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (@USER_ID, @BUYER_ROLE_ID);

-- peter@ppb.com
INSERT INTO ORGANISATIONS(NAME) VALUES ('Pawtucket Patriot Brewery');

INSERT INTO USERS(USER_NAME, PASSWORD, FORENAME, SURNAME)
VALUES ('peter@ppb.com', '$2a$10$nMFDvhatK6bEpLjUX/0bLO/C3fcPDyO8neG/Wck4sRQ2v5CvHi4be', 'Peter', 'Griffin');


