INSERT INTO VAT_RATES(ID, VAT_CODE, RATE) VALUES (1, 'STANDARD', 20.00);
INSERT INTO VAT_RATES(ID, VAT_CODE, RATE) VALUES (2, 'REDUCED', 5.00);
INSERT INTO VAT_RATES(ID, VAT_CODE, RATE) VALUES (3, 'ZERO', 0.00);
INSERT INTO VAT_RATES(ID, VAT_CODE, RATE) VALUES (4, 'EXEMPT', NULL);