package enersis.envisor.entity;

// Generated May 27, 2015 8:01:12 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BillType generated by hbm2java
 */
@Entity
@Table(name = "BillType")
public class BillType implements Serializable {

	private byte id;
	private String type;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public BillType() {
	}

	public BillType(byte id, String type) {
		this.id = id;
		this.type = type;
	}

	public BillType(byte id, String type, Set<Bill> bills) {
		this.id = id;
		this.type = type;
		this.bills = bills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "billType")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
