package enersis.envisor.entity;

// Generated Apr 28, 2015 10:59:09 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "Building")
public class Building implements Serializable {

	private int id;
	private String name;
	private byte flatCount;
	private Byte status;
	private Date transactionTime;
	private Set<Flat> flats = new HashSet<Flat>(0);
	private Set<DistributionLineBuilding> distributionLineBuildings = new HashSet<DistributionLineBuilding>(
			0);

	private byte floorCount;
	private Project project;  // Added by TatvaSoft, used to set Primary Key- Foreign Key relation between Building and Project table.
	private Set<Floor> floors = new HashSet<Floor>(0); // Added by TatvaSoft, used to set Primary Key- Foreign Key relation between Building and Floor table.
	private String imageType;  // Added by TatvaSoft, used to set Image Type of selected Building Image.
	private int imageTop; // Added by TatvaSoft, used to set Image Top (top according to display) of selected Building Image.
	private int imageLeft; // Added by TatvaSoft, used to set Image Left (left according to display) of selected Building Image.
	private int imageWidth; // Added by TatvaSoft, used to set Image Width of selected Building Image.
	private int imageHeight; // Added by TatvaSoft, used to set Image Height of selected Building Image.
	private String imageDivId; // Added by TatvaSoft, used to set HTML Component 'Div' ID of selected Building Image.


	public Building() {
	}

	public Building(int id, String name, byte flatCount) {
		this.id = id;
		this.name = name;
		this.flatCount = flatCount;
	}

	public Building(int id, String name, byte flatCount, Byte status,
			Date transactionTime, Set<Flat> flats,
			Set<DistributionLineBuilding> distributionLineBuildings) {
		this.id = id;
		this.name = name;
		this.flatCount = flatCount;
		this.status = status;
		this.transactionTime = transactionTime;
		this.flats = flats;
		this.distributionLineBuildings = distributionLineBuildings;
	}

	// Added by TatvaSoft, Following constructor can use with DragDrop functionalities.
	public Building(int id, String name, byte flatCount, Byte status,
			Date transactionTime, Set<Flat> flats,
			Set<DistributionLineBuilding> distributionLineBuildings,
			byte floorCount, Project project, Set<Floor> floors,
			String imageType, int imageTop, int imageLeft, int imageWidth,
			int imageHeight) {
		
		this.id = id;
		this.name = name;
		this.flatCount = flatCount;
		this.status = status;
		this.transactionTime = transactionTime;
		this.flats = flats;
		this.distributionLineBuildings = distributionLineBuildings;
		this.floorCount = floorCount;
		this.project = project;
		this.floors = floors;
		this.imageType = imageType;
		this.imageTop = imageTop;
		this.imageLeft = imageLeft;
		this.imageWidth = imageWidth;
		this.imageHeight = imageHeight;
		
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "flatCount", nullable = false)
	public byte getFlatCount() {
		return this.flatCount;
	}

	public void setFlatCount(byte flatCount) {
		this.flatCount = flatCount;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "building")
	public Set<Flat> getFlats() {
		return this.flats;
	}

	public void setFlats(Set<Flat> flats) {
		this.flats = flats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "building")
	public Set<DistributionLineBuilding> getDistributionLineBuildings() {
		return this.distributionLineBuildings;
	}

	public void setDistributionLineBuildings(
			Set<DistributionLineBuilding> distributionLineBuildings) {
		this.distributionLineBuildings = distributionLineBuildings;
	}

	@Column(name = "floorCount", nullable = true)
	public byte getFloorCount() {
		return this.flatCount;
	}

	public void setFloorCount(byte floorCount) {
		this.floorCount = floorCount;
	}

	//Added by TatvaSoft, Following getter-setter used to set Primary Key- Foreign Key relation between Project and Building table.
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "projectId")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	//Added by TatvaSoft, Following getter-setter used to set Primary Key- Foreign Key relation between Building and Floor table.
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "building")
	public Set<Floor> getFloors() {
		return this.floors;
	}

	public void setFloors(Set<Floor> floors) {
		this.floors = floors;
	}

	//Added by TatvaSoft, Following getters-setters used to set Image top,left,width and height : starts.
	@Column(name = "imageType")
	public String getImageType() {
		return imageType;
	}

	public void setImageType(String imageType) {
		this.imageType = imageType;
	}

	@Column(name = "imageTop")
	public int getImageTop() {
		return imageTop;
	}

	public void setImageTop(int imageTop) {
		this.imageTop = imageTop;
	}

	@Column(name = "imageLeft")
	public int getImageLeft() {
		return imageLeft;
	}

	public void setImageLeft(int imageLeft) {
		this.imageLeft = imageLeft;
	}

	@Column(name = "imageWidth")
	public int getImageWidth() {
		return imageWidth;
	}

	public void setImageWidth(int imageWidth) {
		this.imageWidth = imageWidth;
	}

	@Column(name = "imageHeight")
	public int getImageHeight() {
		return imageHeight;
	}

	public void setImageHeight(int imageHeight) {
		this.imageHeight = imageHeight;
	}
	
	@Transient
	public String getImageDivId() {
		return imageDivId;
	}

	public void setImageDivId(String imageDivId) {
		this.imageDivId = imageDivId;
	}

	//Added by TatvaSoft, Following getters-setters used to set Image top,left,width and height : end.

}
