package enersis.envisor.entity;

// Generated Apr 28, 2015 10:59:09 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HeatCostAllocatorReading generated by hbm2java
 */
@Entity
@Table(name = "HeatCostAllocatorReading")
public class HeatCostAllocatorReading implements Serializable {

	private int id;
	private HeatCostAllocator heatCostAllocator;
	private Period period;
	private Date date;
	private int value;
	private byte status;
	private Date transactionTime;

	public HeatCostAllocatorReading() {
	}

	public HeatCostAllocatorReading(int id,
			HeatCostAllocator heatCostAllocator, Period period, Date date,
			int value, byte status, Date transactionTime) {
		this.id = id;
		this.heatCostAllocator = heatCostAllocator;
		this.period = period;
		this.date = date;
		this.value = value;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "heatCostAllocatorID", nullable = false)
	public HeatCostAllocator getHeatCostAllocator() {
		return this.heatCostAllocator;
	}

	public void setHeatCostAllocator(HeatCostAllocator heatCostAllocator) {
		this.heatCostAllocator = heatCostAllocator;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "periodId", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
