package enersis.envisor.entity;

// Generated Apr 28, 2015 10:59:09 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HeatMeter generated by hbm2java
 */
@Entity
@Table(name = "HeatMeter")
public class HeatMeter implements Serializable {

	private int id;
	private Flat flat;
	private String serialNo;
	private byte status;
	private Date transactionTime;
	private Set<HeatMeterReading> heatMeterReadings = new HashSet<HeatMeterReading>(
			0);

	public HeatMeter() {
	}

	public HeatMeter(int id, Flat flat, String serialNo, byte status,
			Date transactionTime) {
		this.id = id;
		this.flat = flat;
		this.serialNo = serialNo;
		this.status = status;
		this.transactionTime = transactionTime;
	}

	public HeatMeter(int id, Flat flat, String serialNo, byte status,
			Date transactionTime, Set<HeatMeterReading> heatMeterReadings) {
		this.id = id;
		this.flat = flat;
		this.serialNo = serialNo;
		this.status = status;
		this.transactionTime = transactionTime;
		this.heatMeterReadings = heatMeterReadings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flatId", nullable = false)
	public Flat getFlat() {
		return this.flat;
	}

	public void setFlat(Flat flat) {
		this.flat = flat;
	}

	@Column(name = "serialNo", nullable = false)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionTime", nullable = false, length = 23)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "heatMeter")
	public Set<HeatMeterReading> getHeatMeterReadings() {
		return this.heatMeterReadings;
	}

	public void setHeatMeterReadings(Set<HeatMeterReading> heatMeterReadings) {
		this.heatMeterReadings = heatMeterReadings;
	}

}
