CREATE TABLE VAT_RATES (
  ID SERIAL NOT NULL,
  VAT_CODE VARCHAR(32) NOT NULL,
  RATE NUMERIC(4,2) NULL,

  CONSTRAINT PK_VAT_RATES PRIMARY KEY (ID),
  CONSTRAINT UQ_VAT_RATES_VAT_CODE UNIQUE (VAT_CODE)
);