ALTER TABLE ORDERS ADD COLUMN BUYER_ORGANISATION_ID INTEGER;
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_BUYER_ORGANISATION FOREIGN KEY (BUYER_ORGANISATION_ID) REFERENCES ORGANISATIONS (ID);

ALTER TABLE ORDERS ADD COLUMN VENDOR_ID INTEGER;
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS (ID);