ALTER TABLE PRODUCTS ADD COLUMN REVIEW VARCHAR(4096);
ALTER TABLE PRODUCTS ADD COLUMN SUITABILITY VARCHAR(4096);
ALTER TABLE PRODUCTS ADD COLUMN PROCESS_NOTIFICATION BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE PRODUCTS ADD COLUMN SUBMIT_NOTIFICATION BOOLEAN NOT NULL DEFAULT FALSE;