ALTER TABLE ORDER_LINE_CREDITS DROP CONSTRAINT FK_ORDER_LINE_CREDITS_ORDER_LINES;

ALTER TABLE ORDER_LINE_CREDITS ADD CONSTRAINT FK_ORDER_LINE_CREDITS_ORDER_LINES FOREIGN KEY (ORDER_LINE_ID) REFERENCES ORDER_LINES(ID);
