ALTER TABLE ADDRESSES ADD COLUMN BUYER_ID INTEGER;
ALTER TABLE ADDRESSES
  ADD CONSTRAINT FK_ADDRESSES_BUYER FOREIGN KEY (BUYER_ID) REFERENCES BUYER_PROFILES (ID);
ALTER TABLE ADDRESSES
  ADD CONSTRAINT UNIQUE_BUYER_DEPARTMENT UNIQUE(DEPARTMENT_NAME, BUYER_ID);