CREATE TABLE ORDER_RETURNS
(
  ID                SERIAL        NOT NULL,
  ORDER_ID          INTEGER       NOT NULL,
  QUANTITY 			INTEGER		  NOT NULL,
  ORDER_LINES_ID	INTEGER       NOT NULL,
  
  CONSTRAINT PK_ORDER_RETURNS PRIMARY KEY (ID),
  CONSTRAINT FK_ORDER_RETURNS_ORDERS FOREIGN KEY (ORDER_ID)
      REFERENCES ORDERS(ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_ORDER_RERURNS_ORDER_LINES FOREIGN KEY (ORDER_LINES_ID)
      REFERENCES ORDER_LINES(ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
