CREATE TABLE OFFERS (
  ID        SERIAL      NOT NULL,
  VERSION   INTEGER      NOT NULL,
  PRODUCT_ID INTEGER     NOT NULL,
  START_DATE_TIME TIMESTAMP NULL,
  END_DATE_TIME TIMESTAMP NULL,
  CURRENT_VOLUME INTEGER NOT NULL,

  CONSTRAINT PK_OFFERS PRIMARY KEY (ID),
  CONSTRAINT FK_OFFERS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);