ALTER TABLE ORDER_LINES ADD COLUMN PRICE_BAND_ID INTEGER NOT NULL;
ALTER TABLE ORDER_LINES ADD CONSTRAINT FK_ORDER_LINES_OFFER_PRICE_BANDS FOREIGN KEY (PRICE_BAND_ID) REFERENCES OFFER_PRICE_BANDS(ID);