ALTER TABLE BUYER_APPLIED_CREDITS DROP COLUMN ORDER_ID;
ALTER TABLE BUYER_APPLIED_CREDITS ADD COLUMN ORIGINAL_ORDER_REFERENCE VARCHAR(36) NULL;
ALTER TABLE BUYER_APPLIED_CREDITS ADD COLUMN ORIGINAL_ORDER_LINE_PRODUCT_CODE VARCHAR(64) NULL;
ALTER TABLE BUYER_APPLIED_CREDITS ADD COLUMN ORDER_SPENT_ON_REFERENCE VARCHAR(36) NULL;
ALTER TABLE BUYER_APPLIED_CREDITS ADD COLUMN MODIFIED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
