INSERT INTO VAT_RATES (VAT_CODE, RATE) VALUES ('STANDARD', 20);
INSERT INTO VAT_RATES (VAT_CODE, RATE) VALUES ('REDUCED', 5);
INSERT INTO VAT_RATES (VAT_CODE, RATE) VALUES ('ZERO', 0);
INSERT INTO VAT_RATES (VAT_CODE, RATE) VALUES ('EXEMPT', null);
