ALTER TABLE USERS ADD COLUMN BUYER_REFERRAL_CODE character varying(20);
ALTER TABLE USERS ADD COLUMN APPLIED_REFERRAL_CODE character varying(20);
ALTER TABLE USERS ADD COLUMN APPLIED_FOR character varying(20);
ALTER TABLE USERS ADD COLUMN VENDOR_ID INTEGER;
ALTER TABLE USERS ADD CONSTRAINT FK_PRODUCT_VENDORS FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(ID);
