CREATE TABLE BUYER_VENDOR_CREDIT
(
  ID 				serial 				NOT NULL,
  VENDOR_ID 		INTEGER 			NOT NULL DEFAULT 0,
  BUYER_ID 			INTEGER 			NOT NULL DEFAULT 0,
  TOTAL_CREDIT 		NUMERIC(9,2) 		NOT NULL,
  AVAILABLE_CREDIT 	NUMERIC(9,2),
  PAYMENT_DUE_DAYS 	INTEGER,
  
  CONSTRAINT PK_BUYER_VENDOR_CREDIT PRIMARY KEY (ID),
  CONSTRAINT FK_BUYER_VENDOR_CREDIT_VENDOR FOREIGN KEY (VENDOR_ID)
      REFERENCES VENDORS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_BUYER_VENDOR_CREDIT_BUYER FOREIGN KEY (BUYER_ID)
      REFERENCES BUYER_PROFILES (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)