ALTER TABLE BANK_ACCOUNTS ALTER COLUMN ACCOUNT_NAME TYPE VARCHAR(64) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN SORTCODE TYPE VARCHAR(8) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN ACCOUNT_NUMBER TYPE VARCHAR(8) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN BANK_NAME TYPE VARCHAR(64) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN BUILDING_NAME TYPE VARCHAR(64) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN STREET_ADDRESS TYPE VARCHAR(128) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN POST_TOWN TYPE VARCHAR(64) ;
ALTER TABLE BANK_ACCOUNTS ALTER COLUMN POST_CODE TYPE VARCHAR(8) ;
